Attendance/urls.py
# urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('register', views.register),
    path('<str:sTitle>', views.attendance),
    path('', views.attendance_list),
]

Home/urls.py
# urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.Home),
]

TeacherWait/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Wait/', include('Wait.urls')),
    path('Attendance/', include('Attendance.urls')),
    path('', include('Home.urls')),
]

Wait/urls.py
# urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.wait),
]

Attendance/models.py
from django.db import models

class Student(models.Model):
	CLASSNUMBER_CHOICE = (
		('1', '二年九班'),
		('2', '一年五班'),
		('3', '一年十二班'),
	)
	sStudent_id = models.CharField(verbose_name = '學號', max_length = 16, primary_key = True)
	sName = models.CharField(verbose_name = '姓名', max_length = 16)
	iSeat_number = models.IntegerField(verbose_name = "座號", null = True, blank = True)
	cClass = models.CharField(max_length = 2, verbose_name = "班級", choices = CLASSNUMBER_CHOICE, blank = True, null = True)
	hashPassword = models.CharField(max_length = 64, verbose_name = "密碼", blank=True, null=True)
	def __str__(self):
		cClass = ''
		if self.cClass == '1':
			cClass = '二年九班'
		elif self.cClass == '2':
			cClass = '一年五班'
		elif self.cClass == '3':
			cClass = '一年十二班'
		return cClass+'_'+self.sStudent_id+self.sName

class Attendance(models.Model):
	CLASSNUMBER_CHOICE = (
		('1', '二年九班'),
		('2', '一年五班'),
		('3', '一年十二班'),
	)
	sTitle = models.TextField(verbose_name = "名稱")
	sDate = models.DateTimeField(verbose_name = '上課日期', null = True)
	cClass = models.CharField(max_length = 2, verbose_name = "班級", choices = CLASSNUMBER_CHOICE, blank = True, null = True)
	iNode = models.IntegerField(verbose_name = "節數", null = True, blank = True)
	def __str__(self):
		return self.sTitle

class Student_Attendance(models.Model):
	sStudent_id = models.ForeignKey(Student, verbose_name = '學生', on_delete = models.CASCADE)
	sAttendance = models.ForeignKey(Attendance, verbose_name = '出席表', on_delete = models.CASCADE)
	bArrived = models.BooleanField(verbose_name = '是否出席', default = False)
	sTime = models.DateTimeField(verbose_name = '簽到時間', auto_now = False, blank=True, null=True)

Home/models.py
from django.db import models

# Create your models here.

Wait/models.py
from django.db import models

# Create your models here.

Attendance/forms.py
# form.py
from django import forms
from Attendance.models import *
from datetime import datetime

class RegisterForm(forms.Form):
	CLASSNUMBER_CHOICE = (
		('1', '二年九班'),
		('2', '一年五班'),
		('3', '一年十二班'),
	)
	sStudent_id = forms.CharField(label = "學號", max_length = 16, widget = forms.TextInput(attrs={'id' : 'sStudent_id', 'class':'form-control','placeholder':'輸入學號'}))
	cClass = forms.ChoiceField(label = '班級', choices = CLASSNUMBER_CHOICE, widget = forms.Select(attrs={'id': 'cClass', 'class':'form-control',}))
	iSeat_number = forms.IntegerField(label = "座號", widget = forms.NumberInput(attrs={'id':'iSeat_number', 'class':'form-control',}))
	sName = forms.CharField(label = '姓名', max_length = 16, widget = forms.TextInput(attrs={'class':'form-control',}))
	hashPassword = forms.CharField(label = "密碼（大於7個字）", max_length = 256, widget = forms.PasswordInput(attrs={'id' : 'hashPassword','class':'form-control','placeholder':'輸入密碼'}))

Attendance/views.py
from django.shortcuts import render
from Attendance.forms import RegisterForm
from .models import *
from datetime import datetime
import hashlib
from django.utils import timezone

def register(request):
	if request.method == "POST":
		registerForm = RegisterForm(request.POST)

		errors = []
		if not registerForm.is_valid():
			errors.extend(registerForm.errors.values())
			return render(request, 'Attendance/register.html', locals())

		else:
			sStudent_id = registerForm.cleaned_data['sStudent_id']
			cClass = registerForm.cleaned_data['cClass']
			iSeat_number = registerForm.cleaned_data['iSeat_number']
			sName = registerForm.cleaned_data['sName']
			hashPassword = registerForm.cleaned_data['hashPassword']

		if (len(hashPassword) < 8):
			errors.append('不是跟你說密碼要大於7個字ㄇ😠')
			return render(request, 'Attendance/register.html', locals())

		filterSameUser = Student.objects.filter(sStudent_id = sStudent_id)
		if (len(filterSameUser) > 0):
			errors.append('使用此學號的使用者已存在。')
			return render(request, 'Attendance/register.html', locals())

		student = Student()
		student.sStudent_id = sStudent_id
		student.cClass = cClass
		student.iSeat_number = iSeat_number
		student.sName = sName
		student.hashPassword = hashlib.sha1(hashPassword.encode()).hexdigest()
		student.save()

		message = ["註冊成功（應該啦）",]

	registerForm = RegisterForm(request.POST)
	return render(request, 'Attendance/register.html', locals())

def attendance(request, sTitle):
	if len(Attendance.objects.filter(sTitle = sTitle)) == 0:
		return render(request, 'Attendance/error.html', locals())
	# get Attendance
	attendance_data = Attendance.objects.filter(sTitle = sTitle)[0]
	cClass = attendance_data.cClass
	student_list = attendance_data.student_attendance_set.order_by('sStudent_id__iSeat_number')
	total_num = len(student_list)
	arrived_num = len(student_list.filter(bArrived = True))

	# new create Attendance or someone new sgin up
	if len(student_list) != len(Student.objects.filter(cClass = cClass)):
		for student in (Student.objects.filter(cClass = cClass)):
			obj, created = student_list.get_or_create(
					sStudent_id = student,
					sAttendance = attendance_data,
				)

	# sign in
	success = True
	if request.POST != {}:
		if attendance_data.sDate < timezone.now():
			success = False
			status = '本節課已經結束，無法再簽到！'
			return render(request, 'Attendance/attendance.html', locals())
		else:
			sStudent_id = request.POST['sStudent_id']
			hashPassword = hashlib.sha1(request.POST['hashPassword'].encode()).hexdigest()
			student = Student.objects.filter(sStudent_id = sStudent_id, hashPassword = hashPassword)

			if len(student) != 0:
				student = student[0]
				if student_list.filter(sStudent_id = student)[0].bArrived == True:
					success = False
					status = student.sName + ' 已經簽到過了啦！'
				else:
					student_list.filter(sStudent_id = student).update(bArrived = True, sTime = timezone.now())
					status = student.sName + ' 簽到成功！'

				# get Attendance
				attendance_data = Attendance.objects.filter(sTitle = sTitle)[0]
				cClass = attendance_data.cClass
				student_list = attendance_data.student_attendance_set.order_by('sStudent_id__iSeat_number')
				return render(request, 'Attendance/attendance.html', locals())

			else:
				status = '學號或密碼錯誤。或不是本堂課的同學'
				success = False
				return render(request, 'Attendance/attendance.html', locals())

	return render(request, 'Attendance/attendance.html', locals())

def attendance_list(request):
	attendance_209 = Attendance.objects.filter(cClass = '1').order_by('-sDate')
	attendance_105 = Attendance.objects.filter(cClass = '2').order_by('-sDate')
	attendance_112 = Attendance.objects.filter(cClass = '3').order_by('-sDate')
	return render(request, 'Attendance/attendance_list.html', locals())

Home/views.py
from django.shortcuts import render

def Home(request):
	return render(request, 'Home/home.html', locals())

Wait/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests

def LineMessage(token, msg):
    headers = {
        "Authorization": "Bearer "+token,
        "Content-Type":"application/x-www-form-urlencoded"
    }
    payload = {
      'message' : msg,
                    }

    r = requests.post('https://notify-api.line.me/api/notify', headers = headers, params = payload)
    return r.status_code



# print(LineMessage(token, message))

def wait(request):
	# return HttpResponse('Hi')
	token = '2XVY4QM6bkOhFBWdS4DZtDLAbzhB9yqZ817LMI0DXNU'
	message = '測試'
	status = "未傳送"
	if request.POST != {}:
		message = request.POST['some_words']
		if LineMessage(token, message) == 200:
			status = '你的訊息"' + message + '"傳送成功！'
		else:
			status = "奇怪的原因失敗了QQ"
		return render(request, 'Wait/wait.html', locals())
	return render(request, 'Wait/wait.html', locals())

Attendance/templates/Attendance/attendance.html
<!-- attendance.html -->
<!DOCTYPE html>
<html lang="tw">
<head>

  <title>{{attendance_data.get_cClass_display}}簽到表</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">首頁</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Wait">匿名傳Line</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance">簽到列表</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance/register">註冊簽到</a>
    </li>
  </ul>
</nav>

<div class="container">
  <h2>{{attendance_data.get_cClass_display}} 第 {{attendance_data.iNode}} 節數學課</h2>
  <p>Due : {{ attendance_data.sDate }} </p>
  <p>Current Time : <span id='ct7' style="background-color: #FFFFFFFF"></span></p>
  <p>簽到人數/總人數：{{arrived_num}}/{{total_num}}</p>         
  <table class="table table-hover">
    <thead>
      <tr>
        <th>座號</th>
        <th>姓名</th>
        <th>簽到狀態</th>
        <th>簽到時間</th>
      </tr>
    </thead>

    <tbody>
      {% for student in student_list %}
	      <tr>
	        <td>{{student.sStudent_id.iSeat_number}}</td>
	        <td>{{student.sStudent_id.sName}}</td>
	        {% if student.bArrived %}
	        <td class="text-success">到了😎</td>
	        {% else %}
	        <td class="text-danger">沒到😠</td>
	        {% endif %}
          {% if student.sTime %}
          <td style="color: purple">{{student.sTime}}</td>
          {% else %}
          <td class="text-danger">-</td>
          {% endif %}
	       
	      </tr>
	  {% endfor %}
    </tbody>
  </table>
</div>

<div class="container">
  <h2>馬上簽到</h2>
  <p>輸入學號、密碼</p>
  <form class="form-inline" action="" method="POST">
  	{% csrf_token %}
    <input type="text" class="form-control"  placeholder="學號" name="sStudent_id">
    <input type="password" class="form-control"  placeholder="密碼" name="hashPassword">
    <button type="submit" class="btn btn-primary">送出</button>
    <a class="btn btn-outline-info" href="register" >第一次使用？</a>
  </form>
</div>
{% if success %}
<div class="alert alert-success">
{% else %}
<div class="alert alert-danger">
{% endif %}
  <strong>簽到狀態：</strong> {{status}}
</div>



</body>
</html>



<script>function display_ct7() {
var x = new Date()
var ampm = x.getHours( ) >= 12 ? ' PM' : ' AM';
hours = x.getHours( ) % 12;
hours = hours ? hours : 12;
hours=hours.toString().length==1? 0+hours.toString() : hours;

var minutes=x.getMinutes().toString()
minutes=minutes.length==1 ? 0+minutes : minutes;

var seconds=x.getSeconds().toString()
seconds=seconds.length==1 ? 0+seconds : seconds;

var month=(x.getMonth() +1).toString();
month=month.length==1 ? 0+month : month;

var dt=x.getDate().toString();
dt=dt.length==1 ? 0+dt : dt;

var x1=month + "/" + dt + "/" + x.getFullYear(); 
x1 = x1 + " - " +  hours + ":" +  minutes + ":" +  seconds + " " + ampm;
document.getElementById('ct7').innerHTML = x1;
display_c7();
 }
 function display_c7(){
var refresh=1000; // Refresh rate in milli seconds
mytime=setTimeout('display_ct7()',refresh)
}
display_c7()
</script>

Attendance/templates/Attendance/attendance_list.html
<!-- attendance_list.html -->


<!DOCTYPE html>
<html lang="en">
<head>
  <title>各班簽到表</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">首頁</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Wait">匿名傳Line</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance">簽到列表</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance/register">註冊簽到</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <h1>各班簽到表</h1>
  <p>找到自己的班級，點選即可進入簽到表。</p>
  <p>列表按照時間排序，所以點最上面那個就是當節課！</p>
  <div class="row">
    <div class="col-sm-3" style="background-color:lavender;"><h3>二年九班</h3>
    	{% for attend in attendance_209 %}
    	<p>
    		<a href="{{attend.sTitle}}">{{attend.sDate}}</a>
    	</p>
    	{% endfor %}
    </div>

    <div class="col-sm-3" style="background-color:lavenderblush;"><h3>一年五班</h3>
    	{% for attend in attendance_105 %}
    	<p>
    		<a href="{{attend.sTitle}}">{{attend.sDate}}</a>
    	</p>
    	{% endfor %}
    </div>
    <div class="col-sm-3" style="background-color:lavender;"><h3>一年十二班</h3>
    	{% for attend in attendance_112 %}
    	<p>
    		<a href="{{attend.sTitle}}">{{attend.sDate}}</a>
    	</p>
    	{% endfor %}
    </div>
  </div>
</div>

</body>
</html>

Attendance/templates/Attendance/error.html
<!-- error.html -->
<!DOCTYPE html>
<html lang="tw">
<head>

  <title>曄面不存在</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">首頁</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Wait">匿名傳Line</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance">簽到列表</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance/register">註冊簽到</a>
    </li>
  </ul>
</nav>
<h2>本曄面不存在！</h2>
</body>

Attendance/templates/Attendance/register.html
<!-- register.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>註冊</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">首頁</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Wait">匿名傳Line</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance">簽到列表</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance/register">註冊簽到</a>
    </li>
  </ul>
</nav>

<div class="container">
  <h2>簽到表註冊</h2>
  <form action="" method="POST">{% csrf_token %}
    <div class="form-group">
    	{{ registerForm.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">註冊</button>
  </form>
  {% for e in errors %}
  <div class="alert alert-danger">
  	<strong>{{e}}</strong>
  </div>
  {% endfor %}

  {% for m in message %}
  <div class="alert alert-success">
  	<strong>{{ m }}</strong>
  </div>
  {% endfor %}

</div>

</body>
</html>

Home/templates/Home/home.html
<!-- home.html -->
<!DOCTYPE html>
<html lang="tw">
<head>

  <title>首曄</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
  	<li class="nav-item active">
      <a class="nav-link" href="/">首頁</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Wait">匿名傳Line</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance">簽到列表</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance/register">註冊簽到</a>
    </li>
  </ul>
</nav>


<div class="container-fluid">
<h1>冠曄的遠距上課小網站</h1>
  <div class="row">
    <div class="col-sm-3" style="background-color:lavender;"><h3>課本講義習作的檔案</h3>
      
      <p>
        <a href="https://drive.google.com/drive/folders/1XYAbPmjVmU_cQTqMG5fcJTWOkemUSmiA?usp=sharing">課本講義習作</a>
      </p>
      
    </div>

    <div class="col-sm-3" style="background-color:lavenderblush;"><h3>上課錄影檔案及常用連結</h3>
      <p>
        <a href="https://www.microsoft.com/zh-tw/education/products/office">用學校帳號免費註冊下載微軟Office</a>
      </p>     
      <p>
        <a href="https://drive.google.com/drive/folders/1uFXKeuIT0zFsHEbeIr_lRvslYuhKyXmn?usp=sharing">5/30 以前上課錄影(204、210、103、104)</a>
      </p>
      <p>
        <a href="https://drive.google.com/drive/folders/19Bj-XSkCP2lv2jjbhbFMkiHyhN0BIFeV?usp=sharing">209、105、112 上課錄影</a>
      </p>
      <p>
        <a href="https://smhs.teams.com.tw/">翰林雲端</a>
      </p>
      
    </div>
    <div class="col-sm-3" style="background-color:lavender;"><h3>冠曄的資源</h3>
      
      <p>
        <a href="https://discord.gg/VMwugbCz">Discord群組</a>
      </p>
      <p>
        <a href="https://410431135.gitlab.io/mathteacherlin/">冠曄個人網站</a>
      </p>

    </div>
  </div>
</div>

</body>

Wait/templates/Wait/wait.html
<!-- wait.html -->
<!DOCTYPE html>
<html lang="tw">
<head>
  <title>冠曄好可愛</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">首頁</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Wait">匿名傳Line</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance">簽到列表</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/Attendance/register">註冊簽到</a>
    </li>
  </ul>
</nav>

<div class="container">
  <h2>上課有問題馬上跟冠曄說</h2>
  <p>輸入你想講的話：</p>
  <form class="form-inline" action="" method="POST">
  	{% csrf_token %}
    <input type="text" class="form-control"  placeholder="點這邊輸入" name="some_words">
    <button type="submit" class="btn btn-primary">送出</button>
  </form>
</div>
<div class="alert alert-success">
  <strong>傳送狀態：</strong> {{status}}
</div>


  <div>
    <button type="button" class="btn btn-outline-primary" onclick="document.getElementById('poll').innerHTML = getRndInteger(1,40)">抽籤</button>
    <p id="poll"></p>
  </div>
<script>
  function getRndInteger(min, max) {
    return Math.floor(Math.random() * (max - min + 1) ) + min;
}
</script>

</body>
</html>